name: AMBA - General workload Issue 🚀
description: Have an issue, question or suggestion for a specific workload alert or for the overall project? Let us know!
title: "[General workload issue]: "
assignees:
  - arthurclares
labels:
  [
    "AMBA Core"
  ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting this issue!
  - type: checkboxes
    id: existing-checks
    attributes:
      label: Check for previous/existing GitHub issues
      description: By submitting this issue, you confirm that you have [searched for previous/existing GitHub issues](https://github.com/Azure/azure-monitor-baseline-alerts/issues) to avoid creating a duplicate.
      options:
        - label: I have checked for previous/existing GitHub issues
          required: true
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type?
      description: How would you best describe this issue? Is this a...
      options:
        - "Feature Request"
        - "Bug"
        - "Question"
        - "Other"
    validations:
      required: true
  - type: textarea
    id: question-feedback-text
    attributes:
      label: Description
      description: Let us know your question, feedback or suggestion here!
    validations:
      required: true

