---
  name: Update ALZ alerts details table files

  ##########################################
  # Start the job on PR for all branches #
  ##########################################

  # yamllint disable-line rule:truthy
  on:
    pull_request:
      types:
        - opened
        - reopened
        - synchronize
        - ready_for_review
      paths:
        - "services/**.json"

    workflow_dispatch: {}

  ###############
  # Set the Job #
  ###############

  jobs:
    update-alz-alerts-details-table-files:
      name: Update ALZ alerts details table files with new, modified or removed alerts
      runs-on: ubuntu-latest

      steps:
        - name: Check out repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Update files
          shell: pwsh
          run: |
            Import-Module Pester -Force
              $pesterConfiguration = @{
                Run    = @{
                  Container = New-PesterContainer -Path "./tooling/ALZ/Generate-AlertsDetailsTable.ps1"
                  PassThru  = $true
                }
                Output = @{
                  Verbosity = 'Detailed'
                }
              }
              $result = Invoke-Pester -Configuration $pesterConfiguration
              exit $result.FailedCount
